CREATE TABLE IF NOT EXISTS ai_message_schedules (
    schedule_id CHAR(36) NOT NULL,
    company_id CHAR(36) NOT NULL,
    device_id CHAR(36) NOT NULL,
    customer_id CHAR(36) NOT NULL,
    customer_phone_id CHAR(36) NOT NULL,
    dispatch_id CHAR(36) NOT NULL,
    revision BIGINT UNSIGNED NOT NULL DEFAULT 1,
    channel VARCHAR(24) NOT NULL,
    message_class VARCHAR(24) NOT NULL DEFAULT 'TRANSACTIONAL',
    content_ciphertext LONGTEXT NOT NULL,
    fallback_ciphertext LONGTEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'APPROVED',
    device_status VARCHAR(32) NULL,
    scheduled_at DATETIME NOT NULL,
    expires_at DATETIME NOT NULL,
    dispatched_at DATETIME NULL,
    completed_at DATETIME NULL,
    last_error VARCHAR(500) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (schedule_id),
    UNIQUE KEY uq_ai_message_schedules_dispatch (dispatch_id),
    KEY idx_ai_message_schedules_company_time (company_id, scheduled_at),
    KEY idx_ai_message_schedules_device_status (device_id, status, scheduled_at),
    CONSTRAINT fk_ai_message_schedules_company FOREIGN KEY (company_id) REFERENCES ai_companies(company_id),
    CONSTRAINT fk_ai_message_schedules_device FOREIGN KEY (device_id) REFERENCES ai_devices(device_id),
    CONSTRAINT fk_ai_message_schedules_customer FOREIGN KEY (customer_id) REFERENCES ai_customer_directory(customer_id),
    CONSTRAINT fk_ai_message_schedules_phone FOREIGN KEY (customer_phone_id) REFERENCES ai_customer_phones(customer_phone_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_schedule_dispatch_outbox (
    outbox_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    schedule_id CHAR(36) NOT NULL,
    company_id CHAR(36) NOT NULL,
    device_id CHAR(36) NOT NULL,
    dispatch_id CHAR(36) NOT NULL,
    revision BIGINT UNSIGNED NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
    available_at DATETIME NOT NULL,
    lease_token_hash CHAR(64) NULL,
    lease_expires_at DATETIME NULL,
    fcm_message_id VARCHAR(255) NULL,
    last_error VARCHAR(500) NULL,
    acknowledged_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (outbox_id),
    UNIQUE KEY uq_ai_schedule_outbox_dispatch (dispatch_id),
    KEY idx_ai_schedule_outbox_due (status, available_at),
    KEY idx_ai_schedule_outbox_schedule (schedule_id, revision),
    CONSTRAINT fk_ai_schedule_outbox_schedule FOREIGN KEY (schedule_id) REFERENCES ai_message_schedules(schedule_id),
    CONSTRAINT fk_ai_schedule_outbox_company FOREIGN KEY (company_id) REFERENCES ai_companies(company_id),
    CONSTRAINT fk_ai_schedule_outbox_device FOREIGN KEY (device_id) REFERENCES ai_devices(device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
