CREATE TABLE IF NOT EXISTS plugin_payapp_configs (
    config_id  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    domain_id  BIGINT UNSIGNED NOT NULL,
    config_data JSON NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_domain (domain_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
