-- Shop Package - 상품정보제공고시 및 현행(2023-01-01 시행) 40개 품목

CREATE TABLE IF NOT EXISTS shop_product_notice_templates (
    template_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    type_code VARCHAR(50) NOT NULL COMMENT '품목 코드',
    revision VARCHAR(20) NOT NULL COMMENT '고시 양식 버전',
    name VARCHAR(100) NOT NULL COMMENT '품목명',
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '고시 품목 순서',
    effective_from DATE NOT NULL COMMENT '시행일',
    source_title VARCHAR(255) NOT NULL DEFAULT '' COMMENT '근거 고시',
    is_current TINYINT(1) NOT NULL DEFAULT 0 COMMENT '신규 상품 기본 양식',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_notice_template_revision (type_code, revision),
    INDEX idx_notice_template_current (is_current, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='상품정보제공고시 품목 양식';

CREATE TABLE IF NOT EXISTS shop_product_notice_template_fields (
    field_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    template_id BIGINT UNSIGNED NOT NULL,
    field_code VARCHAR(50) NOT NULL COMMENT '버전 간 값 승계용 항목 코드',
    label VARCHAR(255) NOT NULL COMMENT '표시 항목명',
    help_text VARCHAR(500) NOT NULL DEFAULT '' COMMENT '입력 안내',
    input_type VARCHAR(10) NOT NULL DEFAULT 'TEXT' COMMENT '관리자 입력 형식(TEXT/TEXTAREA)',
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_notice_template_field (template_id, field_code),
    INDEX idx_notice_template_field_sort (template_id, sort_order),
    FOREIGN KEY (template_id) REFERENCES shop_product_notice_templates(template_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='상품정보제공고시 양식 항목';

CREATE TABLE IF NOT EXISTS shop_product_notices (
    product_notice_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    domain_id BIGINT UNSIGNED NOT NULL,
    goods_id BIGINT UNSIGNED NOT NULL,
    template_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_product_notice (domain_id, goods_id),
    INDEX idx_product_notice_template (template_id),
    FOREIGN KEY (domain_id) REFERENCES domain_configs(domain_id) ON DELETE CASCADE,
    FOREIGN KEY (goods_id) REFERENCES shop_products(goods_id) ON DELETE CASCADE,
    FOREIGN KEY (template_id) REFERENCES shop_product_notice_templates(template_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='상품별 상품정보제공고시 선택';

CREATE TABLE IF NOT EXISTS shop_product_notice_values (
    value_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    product_notice_id BIGINT UNSIGNED NOT NULL,
    field_code VARCHAR(50) NOT NULL,
    field_value TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_product_notice_value (product_notice_id, field_code),
    FOREIGN KEY (product_notice_id) REFERENCES shop_product_notices(product_notice_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='상품별 상품정보제공고시 입력값';

INSERT INTO shop_product_notice_templates
    (type_code, revision, name, sort_order, effective_from, source_title, is_current)
VALUES
('clothing','2023-01-01','의류',1,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('shoes','2023-01-01','구두/신발',2,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('bag','2023-01-01','가방',3,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('fashion_accessory','2023-01-01','패션잡화(모자/벨트/액세서리 등)',4,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('bedding','2023-01-01','침구류/커튼',5,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('furniture','2023-01-01','가구(침대/소파/싱크대/DIY제품 등)',6,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('image_appliance','2023-01-01','영상가전(TV류)',7,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('home_appliance','2023-01-01','가정용 전기제품(냉장고/세탁기/식기세척기/전자레인지 등)',8,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('seasonal_appliance','2023-01-01','계절가전(에어컨/온풍기 등)',9,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('office_appliance','2023-01-01','사무용기기(컴퓨터/노트북/프린터 등)',10,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('optical_device','2023-01-01','광학기기(디지털카메라/캠코더 등)',11,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('small_electronics','2023-01-01','소형전자(MP3/전자사전 등)',12,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('portable_communication','2023-01-01','휴대형 통신기기(휴대폰/태블릿 등)',13,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('navigation','2023-01-01','내비게이션',14,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('car_accessory','2023-01-01','자동차용품(자동차부품/기타 자동차용품 등)',15,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('medical_device','2023-01-01','의료기기',16,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('kitchenware','2023-01-01','주방용품',17,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('cosmetics','2023-01-01','화장품',18,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('jewelry','2023-01-01','귀금속/보석/시계류',19,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('agricultural_food','2023-01-01','농수축산물',20,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('processed_food','2023-01-01','가공식품',21,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('health_functional_food','2023-01-01','건강기능식품',22,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('children_product','2023-01-01','어린이제품',23,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('musical_instrument','2023-01-01','악기',24,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('sports_goods','2023-01-01','스포츠용품',25,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('book','2023-01-01','서적',26,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('accommodation','2023-01-01','호텔/펜션 예약',27,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('travel_package','2023-01-01','여행패키지',28,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('airline_ticket','2023-01-01','항공권',29,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('car_rental','2023-01-01','자동차 대여 서비스(렌터카)',30,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('rental_appliance','2023-01-01','물품대여 서비스(정수기/비데/공기청정기 등)',31,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('rental_goods','2023-01-01','물품대여 서비스(서적/유아용품/행사용품 등)',32,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('digital_content','2023-01-01','디지털 콘텐츠(음원/게임/인터넷강의 등)',33,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('gift_card','2023-01-01','상품권/쿠폰',34,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('mobile_coupon','2023-01-01','모바일 쿠폰',35,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('movie_performance','2023-01-01','영화/공연',36,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('household_chemical','2023-01-01','생활화학제품',37,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('biocidal_product','2023-01-01','살생물제품',38,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('other_service','2023-01-01','기타 용역',39,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1),
('other_goods','2023-01-01','기타 재화',40,'2023-01-01','전자상거래 등에서의 상품 등의 정보제공에 관한 고시(공정거래위원회고시 제2022-15호)',1);

-- 항목명은 현행 고시의 품목별 표를 그대로 화면에 제공한다.
-- input_type 은 관리자 입력란 형식이며, 여러 줄로 적는 항목만 TEXTAREA 로 둔다.
INSERT INTO shop_product_notice_template_fields (template_id, field_code, label, input_type, sort_order)
SELECT t.template_id, f.field_code, f.label, f.input_type, f.sort_order
FROM shop_product_notice_templates t
JOIN (
SELECT 'clothing' c,'material' field_code,'제품 소재' label,'TEXT' input_type,10 sort_order UNION ALL SELECT 'clothing','color','색상','TEXT',20 UNION ALL SELECT 'clothing','size','치수','TEXT',30 UNION ALL SELECT 'clothing','manufacturer','제조자/수입자','TEXT',40 UNION ALL SELECT 'clothing','country','제조국','TEXT',50 UNION ALL SELECT 'clothing','care','세탁방법 및 취급 시 주의사항','TEXTAREA',60 UNION ALL SELECT 'clothing','manufactured','제조연월','TEXT',70 UNION ALL SELECT 'clothing','warranty','품질보증기준','TEXTAREA',80 UNION ALL SELECT 'clothing','service','A/S 책임자와 전화번호','TEXT',90 UNION ALL
SELECT 'shoes','material','제품 주소재','TEXT',10 UNION ALL SELECT 'shoes','color','색상','TEXT',20 UNION ALL SELECT 'shoes','size','치수','TEXT',30 UNION ALL SELECT 'shoes','manufacturer','제조자/수입자','TEXT',40 UNION ALL SELECT 'shoes','country','제조국','TEXT',50 UNION ALL SELECT 'shoes','care','취급 시 주의사항','TEXTAREA',60 UNION ALL SELECT 'shoes','warranty','품질보증기준','TEXTAREA',70 UNION ALL SELECT 'shoes','service','A/S 책임자와 전화번호','TEXT',80 UNION ALL
SELECT 'bag','item_type','종류','TEXT',10 UNION ALL SELECT 'bag','material','소재','TEXT',20 UNION ALL SELECT 'bag','color','색상','TEXT',30 UNION ALL SELECT 'bag','size','크기','TEXT',40 UNION ALL SELECT 'bag','manufacturer','제조자/수입자','TEXT',50 UNION ALL SELECT 'bag','country','제조국','TEXT',60 UNION ALL SELECT 'bag','care','취급 시 주의사항','TEXTAREA',70 UNION ALL SELECT 'bag','warranty','품질보증기준','TEXTAREA',80 UNION ALL SELECT 'bag','service','A/S 책임자와 전화번호','TEXT',90 UNION ALL
SELECT 'fashion_accessory','item_type','종류','TEXT',10 UNION ALL SELECT 'fashion_accessory','material','소재','TEXT',20 UNION ALL SELECT 'fashion_accessory','size','치수','TEXT',30 UNION ALL SELECT 'fashion_accessory','manufacturer','제조자/수입자','TEXT',40 UNION ALL SELECT 'fashion_accessory','country','제조국','TEXT',50 UNION ALL SELECT 'fashion_accessory','care','취급 시 주의사항','TEXTAREA',60 UNION ALL SELECT 'fashion_accessory','warranty','품질보증기준','TEXTAREA',70 UNION ALL SELECT 'fashion_accessory','service','A/S 책임자와 전화번호','TEXT',80 UNION ALL
SELECT 'bedding','material','제품 소재','TEXT',10 UNION ALL SELECT 'bedding','color','색상','TEXT',20 UNION ALL SELECT 'bedding','size','치수','TEXT',30 UNION ALL SELECT 'bedding','components','제품 구성','TEXT',40 UNION ALL SELECT 'bedding','manufacturer','제조자/수입자','TEXT',50 UNION ALL SELECT 'bedding','country','제조국','TEXT',60 UNION ALL SELECT 'bedding','care','세탁방법 및 취급 시 주의사항','TEXTAREA',70 UNION ALL SELECT 'bedding','warranty','품질보증기준','TEXTAREA',80 UNION ALL SELECT 'bedding','service','A/S 책임자와 전화번호','TEXT',90 UNION ALL
SELECT 'furniture','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'furniture','kc','KC 인증정보','TEXT',20 UNION ALL SELECT 'furniture','size','크기','TEXT',30 UNION ALL SELECT 'furniture','color','색상','TEXT',40 UNION ALL SELECT 'furniture','material','재질','TEXT',50 UNION ALL SELECT 'furniture','components','구성품','TEXT',60 UNION ALL SELECT 'furniture','manufacturer','제조자/수입자','TEXT',70 UNION ALL SELECT 'furniture','country','제조국','TEXT',80 UNION ALL SELECT 'furniture','install','배송·설치 비용','TEXT',90 UNION ALL SELECT 'furniture','warranty','품질보증기준','TEXTAREA',100 UNION ALL SELECT 'furniture','service','A/S 책임자와 전화번호','TEXT',110 UNION ALL SELECT 'furniture','refurbished','재공급(리퍼브) 가구의 재공급 사유 및 하자 부위','TEXTAREA',120 UNION ALL
SELECT 'image_appliance','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'image_appliance','kc','KC 인증정보','TEXT',20 UNION ALL SELECT 'image_appliance','rated','정격전압 및 소비전력','TEXT',30 UNION ALL SELECT 'image_appliance','energy','에너지소비효율등급','TEXT',40 UNION ALL SELECT 'image_appliance','released','동일모델의 출시년월','TEXT',50 UNION ALL SELECT 'image_appliance','manufacturer','제조자/수입자','TEXT',60 UNION ALL SELECT 'image_appliance','country','제조국','TEXT',70 UNION ALL SELECT 'image_appliance','size','크기 및 형태','TEXT',80 UNION ALL SELECT 'image_appliance','screen','화면사양','TEXT',90 UNION ALL SELECT 'image_appliance','install','추가설치비용','TEXT',100 UNION ALL SELECT 'image_appliance','warranty','품질보증기준','TEXTAREA',110 UNION ALL SELECT 'image_appliance','service','A/S 책임자와 전화번호','TEXT',120 UNION ALL
SELECT 'home_appliance','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'home_appliance','kc','KC 인증정보','TEXT',20 UNION ALL SELECT 'home_appliance','rated','정격전압 및 소비전력','TEXT',30 UNION ALL SELECT 'home_appliance','energy','에너지소비효율등급','TEXT',40 UNION ALL SELECT 'home_appliance','released','동일모델의 출시년월','TEXT',50 UNION ALL SELECT 'home_appliance','manufacturer','제조자/수입자','TEXT',60 UNION ALL SELECT 'home_appliance','country','제조국','TEXT',70 UNION ALL SELECT 'home_appliance','size','크기/용량/형태','TEXT',80 UNION ALL SELECT 'home_appliance','install','추가설치비용','TEXT',90 UNION ALL SELECT 'home_appliance','warranty','품질보증기준','TEXTAREA',100 UNION ALL SELECT 'home_appliance','service','A/S 책임자와 전화번호','TEXT',110 UNION ALL
SELECT 'seasonal_appliance','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'seasonal_appliance','kc','KC 인증정보','TEXT',20 UNION ALL SELECT 'seasonal_appliance','rated','정격전압 및 소비전력','TEXT',30 UNION ALL SELECT 'seasonal_appliance','energy','에너지소비효율등급','TEXT',40 UNION ALL SELECT 'seasonal_appliance','released','동일모델의 출시년월','TEXT',50 UNION ALL SELECT 'seasonal_appliance','manufacturer','제조자/수입자','TEXT',60 UNION ALL SELECT 'seasonal_appliance','country','제조국','TEXT',70 UNION ALL SELECT 'seasonal_appliance','size','크기 및 형태(실외기 포함)','TEXT',80 UNION ALL SELECT 'seasonal_appliance','cooling','냉난방면적','TEXT',90 UNION ALL SELECT 'seasonal_appliance','install','추가설치비용','TEXT',100 UNION ALL SELECT 'seasonal_appliance','warranty','품질보증기준','TEXTAREA',110 UNION ALL SELECT 'seasonal_appliance','service','A/S 책임자와 전화번호','TEXT',120 UNION ALL
SELECT 'office_appliance','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'office_appliance','kc','KC 인증정보','TEXT',20 UNION ALL SELECT 'office_appliance','rated','정격전압 및 소비전력','TEXT',30 UNION ALL SELECT 'office_appliance','energy','에너지소비효율등급','TEXT',40 UNION ALL SELECT 'office_appliance','released','동일모델의 출시년월','TEXT',50 UNION ALL SELECT 'office_appliance','manufacturer','제조자/수입자','TEXT',60 UNION ALL SELECT 'office_appliance','country','제조국','TEXT',70 UNION ALL SELECT 'office_appliance','size_weight','크기 및 무게','TEXT',80 UNION ALL SELECT 'office_appliance','spec','주요 사양','TEXTAREA',90 UNION ALL SELECT 'office_appliance','warranty','품질보증기준','TEXTAREA',100 UNION ALL SELECT 'office_appliance','service','A/S 책임자와 전화번호','TEXT',110 UNION ALL
SELECT 'optical_device','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'optical_device','kc','KC 인증정보','TEXT',20 UNION ALL SELECT 'optical_device','rated','정격전압 및 소비전력','TEXT',30 UNION ALL SELECT 'optical_device','manufacturer','제조자/수입자','TEXT',40 UNION ALL SELECT 'optical_device','country','제조국','TEXT',50 UNION ALL SELECT 'optical_device','size_weight','크기 및 무게','TEXT',60 UNION ALL SELECT 'optical_device','spec','주요 사양','TEXTAREA',70 UNION ALL SELECT 'optical_device','warranty','품질보증기준','TEXTAREA',80 UNION ALL SELECT 'optical_device','service','A/S 책임자와 전화번호','TEXT',90 UNION ALL
SELECT 'small_electronics','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'small_electronics','kc','KC 인증정보','TEXT',20 UNION ALL SELECT 'small_electronics','rated','정격전압 및 소비전력','TEXT',30 UNION ALL SELECT 'small_electronics','released','동일모델의 출시년월','TEXT',40 UNION ALL SELECT 'small_electronics','manufacturer','제조자/수입자','TEXT',50 UNION ALL SELECT 'small_electronics','country','제조국','TEXT',60 UNION ALL SELECT 'small_electronics','size_weight','크기 및 무게','TEXT',70 UNION ALL SELECT 'small_electronics','spec','주요 사양','TEXTAREA',80 UNION ALL SELECT 'small_electronics','warranty','품질보증기준','TEXTAREA',90 UNION ALL SELECT 'small_electronics','service','A/S 책임자와 전화번호','TEXT',100 UNION ALL
SELECT 'portable_communication','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'portable_communication','kc','KC 인증정보','TEXT',20 UNION ALL SELECT 'portable_communication','released','동일모델의 출시년월','TEXT',30 UNION ALL SELECT 'portable_communication','manufacturer','제조자/수입자','TEXT',40 UNION ALL SELECT 'portable_communication','country','제조국','TEXT',50 UNION ALL SELECT 'portable_communication','size_weight','크기 및 무게','TEXT',60 UNION ALL SELECT 'portable_communication','carrier','이동통신 가입조건','TEXT',70 UNION ALL SELECT 'portable_communication','spec','주요 사양','TEXTAREA',80 UNION ALL SELECT 'portable_communication','warranty','품질보증기준','TEXTAREA',90 UNION ALL SELECT 'portable_communication','service','A/S 책임자와 전화번호','TEXT',100 UNION ALL
SELECT 'navigation','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'navigation','kc','KC 인증정보','TEXT',20 UNION ALL SELECT 'navigation','rated','정격전압 및 소비전력','TEXT',30 UNION ALL SELECT 'navigation','released','동일모델의 출시년월','TEXT',40 UNION ALL SELECT 'navigation','manufacturer','제조자/수입자','TEXT',50 UNION ALL SELECT 'navigation','country','제조국','TEXT',60 UNION ALL SELECT 'navigation','size_weight','크기 및 무게','TEXT',70 UNION ALL SELECT 'navigation','spec','주요 사양','TEXTAREA',80 UNION ALL SELECT 'navigation','map_update','맵 업데이트 비용 및 무상기간','TEXT',90 UNION ALL SELECT 'navigation','warranty','품질보증기준','TEXTAREA',100 UNION ALL SELECT 'navigation','service','A/S 책임자와 전화번호','TEXT',110 UNION ALL
SELECT 'car_accessory','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'car_accessory','released','동일모델의 출시년월','TEXT',20 UNION ALL SELECT 'car_accessory','kc','KC 인증정보','TEXT',30 UNION ALL SELECT 'car_accessory','manufacturer','제조자/수입자','TEXT',40 UNION ALL SELECT 'car_accessory','country','제조국','TEXT',50 UNION ALL SELECT 'car_accessory','size','크기','TEXT',60 UNION ALL SELECT 'car_accessory','vehicle','적용 차종','TEXT',70 UNION ALL SELECT 'car_accessory','care','제품사용으로 인한 위험 및 유의사항','TEXTAREA',80 UNION ALL SELECT 'car_accessory','warranty','품질보증기준','TEXTAREA',90 UNION ALL SELECT 'car_accessory','inspection','검사합격증 번호','TEXT',100 UNION ALL SELECT 'car_accessory','service','A/S 책임자와 전화번호','TEXT',110 UNION ALL
SELECT 'medical_device','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'medical_device','license','허가·인증·신고번호','TEXT',20 UNION ALL SELECT 'medical_device','rated','정격전압 및 소비전력','TEXT',30 UNION ALL SELECT 'medical_device','released','동일모델의 출시년월','TEXT',40 UNION ALL SELECT 'medical_device','manufacturer','제조자/수입자','TEXT',50 UNION ALL SELECT 'medical_device','country','제조국','TEXT',60 UNION ALL SELECT 'medical_device','purpose','제품의 사용목적 및 사용방법','TEXTAREA',70 UNION ALL SELECT 'medical_device','care','취급 시 주의사항','TEXTAREA',80 UNION ALL SELECT 'medical_device','warranty','품질보증기준','TEXTAREA',90 UNION ALL SELECT 'medical_device','service','A/S 책임자와 전화번호','TEXT',100 UNION ALL
SELECT 'kitchenware','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'kitchenware','material','재질','TEXT',20 UNION ALL SELECT 'kitchenware','components','구성품','TEXT',30 UNION ALL SELECT 'kitchenware','size','크기','TEXT',40 UNION ALL SELECT 'kitchenware','released','동일모델의 출시년월','TEXT',50 UNION ALL SELECT 'kitchenware','manufacturer','제조자/수입자','TEXT',60 UNION ALL SELECT 'kitchenware','country','제조국','TEXT',70 UNION ALL SELECT 'kitchenware','import_notice','수입 기구·용기의 수입신고 여부','TEXT',80 UNION ALL SELECT 'kitchenware','warranty','품질보증기준','TEXTAREA',90 UNION ALL SELECT 'kitchenware','service','A/S 책임자와 전화번호','TEXT',100 UNION ALL
SELECT 'cosmetics','capacity','내용물의 용량 또는 중량','TEXT',10 UNION ALL SELECT 'cosmetics','spec','제품 주요 사양','TEXTAREA',20 UNION ALL SELECT 'cosmetics','expiry','사용기한 또는 개봉 후 사용기간','TEXT',30 UNION ALL SELECT 'cosmetics','usage','사용방법','TEXTAREA',40 UNION ALL SELECT 'cosmetics','business','화장품제조업자/책임판매업자/맞춤형화장품판매업자','TEXTAREA',50 UNION ALL SELECT 'cosmetics','country','제조국','TEXT',60 UNION ALL SELECT 'cosmetics','ingredients','화장품법에 따라 기재·표시하여야 하는 모든 성분','TEXTAREA',70 UNION ALL SELECT 'cosmetics','functional','기능성 화장품 심사 여부','TEXT',80 UNION ALL SELECT 'cosmetics','care','사용할 때의 주의사항','TEXTAREA',90 UNION ALL SELECT 'cosmetics','warranty','품질보증기준','TEXTAREA',100 UNION ALL SELECT 'cosmetics','service','소비자 상담 관련 전화번호','TEXT',110 UNION ALL
SELECT 'jewelry','material','소재/순도/밴드재질','TEXT',10 UNION ALL SELECT 'jewelry','weight','중량','TEXT',20 UNION ALL SELECT 'jewelry','manufacturer','제조자/수입자','TEXT',30 UNION ALL SELECT 'jewelry','country','제조국','TEXT',40 UNION ALL SELECT 'jewelry','size','치수','TEXT',50 UNION ALL SELECT 'jewelry','care','착용 시 주의사항','TEXTAREA',60 UNION ALL SELECT 'jewelry','spec','주요 사양','TEXTAREA',70 UNION ALL SELECT 'jewelry','warranty_service','보증서 제공 여부','TEXT',80 UNION ALL SELECT 'jewelry','warranty','품질보증기준','TEXTAREA',90 UNION ALL SELECT 'jewelry','service','A/S 책임자와 전화번호','TEXT',100 UNION ALL
SELECT 'agricultural_food','name','품목 또는 명칭','TEXT',10 UNION ALL SELECT 'agricultural_food','capacity','포장단위별 내용물의 용량/수량/크기','TEXT',20 UNION ALL SELECT 'agricultural_food','producer','생산자/수입자','TEXT',30 UNION ALL SELECT 'agricultural_food','origin','원산지','TEXT',40 UNION ALL SELECT 'agricultural_food','manufactured','제조연월일/소비기한/품질유지기한','TEXT',50 UNION ALL SELECT 'agricultural_food','grade','세부 품목군별 표시사항','TEXTAREA',60 UNION ALL SELECT 'agricultural_food','components','상품구성','TEXT',70 UNION ALL SELECT 'agricultural_food','storage','보관방법 또는 취급방법','TEXTAREA',80 UNION ALL SELECT 'agricultural_food','care','소비자 안전을 위한 주의사항','TEXTAREA',90 UNION ALL SELECT 'agricultural_food','service','소비자 상담 관련 전화번호','TEXT',100 UNION ALL
SELECT 'processed_food','labeling','식품표시광고법에 따른 표시사항','TEXTAREA',10 UNION ALL SELECT 'processed_food','import_notice','수입식품의 수입신고 여부','TEXT',20 UNION ALL SELECT 'processed_food','service','소비자 상담 관련 전화번호','TEXT',30 UNION ALL
SELECT 'health_functional_food','labeling','식품표시광고법 및 건강기능식품법에 따른 표시사항','TEXTAREA',10 UNION ALL SELECT 'health_functional_food','genetic','유전자변형건강기능식품 표시','TEXT',20 UNION ALL SELECT 'health_functional_food','import_notice','수입 건강기능식품의 수입신고 여부','TEXT',30 UNION ALL SELECT 'health_functional_food','service','소비자 상담 관련 전화번호','TEXT',40 UNION ALL
SELECT 'children_product','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'children_product','kc','KC 인증정보','TEXT',20 UNION ALL SELECT 'children_product','size_weight','크기/중량','TEXT',30 UNION ALL SELECT 'children_product','color','색상','TEXT',40 UNION ALL SELECT 'children_product','material','재질','TEXT',50 UNION ALL SELECT 'children_product','age','사용연령 또는 권장사용연령','TEXT',60 UNION ALL SELECT 'children_product','limit','크기·체중의 한계','TEXT',70 UNION ALL SELECT 'children_product','released','동일모델의 출시년월','TEXT',80 UNION ALL SELECT 'children_product','manufacturer','제조자/수입자','TEXT',90 UNION ALL SELECT 'children_product','country','제조국','TEXT',100 UNION ALL SELECT 'children_product','care','취급방법 및 취급 시 주의사항/안전표시','TEXTAREA',110 UNION ALL SELECT 'children_product','warranty','품질보증기준','TEXTAREA',120 UNION ALL SELECT 'children_product','service','A/S 책임자와 전화번호','TEXT',130 UNION ALL
SELECT 'musical_instrument','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'musical_instrument','size','크기','TEXT',20 UNION ALL SELECT 'musical_instrument','color','색상','TEXT',30 UNION ALL SELECT 'musical_instrument','material','재질','TEXT',40 UNION ALL SELECT 'musical_instrument','components','제품 구성','TEXT',50 UNION ALL SELECT 'musical_instrument','released','동일모델의 출시년월','TEXT',60 UNION ALL SELECT 'musical_instrument','manufacturer','제조자/수입자','TEXT',70 UNION ALL SELECT 'musical_instrument','country','제조국','TEXT',80 UNION ALL SELECT 'musical_instrument','spec','상품별 세부 사양','TEXTAREA',90 UNION ALL SELECT 'musical_instrument','warranty','품질보증기준','TEXTAREA',100 UNION ALL SELECT 'musical_instrument','service','A/S 책임자와 전화번호','TEXT',110 UNION ALL
SELECT 'sports_goods','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'sports_goods','kc','KC 인증정보','TEXT',20 UNION ALL SELECT 'sports_goods','size_weight','크기 및 중량','TEXT',30 UNION ALL SELECT 'sports_goods','color','색상','TEXT',40 UNION ALL SELECT 'sports_goods','material','재질','TEXT',50 UNION ALL SELECT 'sports_goods','components','제품 구성','TEXT',60 UNION ALL SELECT 'sports_goods','released','동일모델의 출시년월','TEXT',70 UNION ALL SELECT 'sports_goods','manufacturer','제조자/수입자','TEXT',80 UNION ALL SELECT 'sports_goods','country','제조국','TEXT',90 UNION ALL SELECT 'sports_goods','spec','상품별 세부 사양','TEXTAREA',100 UNION ALL SELECT 'sports_goods','warranty','품질보증기준','TEXTAREA',110 UNION ALL SELECT 'sports_goods','service','A/S 책임자와 전화번호','TEXT',120 UNION ALL
SELECT 'book','title','도서명','TEXT',10 UNION ALL SELECT 'book','author','저자/출판사','TEXT',20 UNION ALL SELECT 'book','size','크기','TEXT',30 UNION ALL SELECT 'book','pages','쪽수','TEXT',40 UNION ALL SELECT 'book','components','제품 구성','TEXT',50 UNION ALL SELECT 'book','published','발행일','TEXT',60 UNION ALL SELECT 'book','summary','목차 또는 책 소개','TEXTAREA',70 UNION ALL
SELECT 'accommodation','destination','국가 또는 지역명','TEXT',10 UNION ALL SELECT 'accommodation','lodging_type','숙소 형태','TEXT',20 UNION ALL SELECT 'accommodation','room','등급/객실 타입','TEXT',30 UNION ALL SELECT 'accommodation','cost','사용가능 인원 및 인원 추가 비용','TEXT',40 UNION ALL SELECT 'accommodation','facilities','부대시설/제공 서비스','TEXTAREA',50 UNION ALL SELECT 'accommodation','cancel','취소 규정','TEXTAREA',60 UNION ALL SELECT 'accommodation','contact','예약 담당 연락처','TEXT',70 UNION ALL
SELECT 'travel_package','agency','여행사','TEXT',10 UNION ALL SELECT 'travel_package','certificate','이용항공편','TEXT',20 UNION ALL SELECT 'travel_package','period','여행기간 및 일정','TEXTAREA',30 UNION ALL SELECT 'travel_package','minimum','총 예정 인원/출발 가능 인원','TEXT',40 UNION ALL SELECT 'travel_package','hotel','숙박정보','TEXTAREA',50 UNION ALL SELECT 'travel_package','price','여행상품 가격','TEXT',60 UNION ALL SELECT 'travel_package','optional','선택경비 유무 및 세부 내용','TEXTAREA',70 UNION ALL SELECT 'travel_package','cancel','취소 규정','TEXTAREA',80 UNION ALL SELECT 'travel_package','warning','해외여행 시 외교부 지정 여행경보단계','TEXTAREA',90 UNION ALL SELECT 'travel_package','contact','예약 담당 연락처','TEXT',100 UNION ALL
SELECT 'airline_ticket','round_trip','왕복/편도 여부','TEXT',10 UNION ALL SELECT 'airline_ticket','validity','유효기간','TEXT',20 UNION ALL SELECT 'airline_ticket','restriction','제한사항','TEXTAREA',30 UNION ALL SELECT 'airline_ticket','ticketing','티켓수령방법','TEXT',40 UNION ALL SELECT 'airline_ticket','seat','좌석종류','TEXT',50 UNION ALL SELECT 'airline_ticket','excluded','가격에 포함되지 않은 내용 및 금액','TEXTAREA',60 UNION ALL SELECT 'airline_ticket','cancel','취소 규정','TEXTAREA',70 UNION ALL SELECT 'airline_ticket','contact','예약 담당 연락처','TEXT',80 UNION ALL
SELECT 'car_rental','vehicle','차종','TEXT',10 UNION ALL SELECT 'car_rental','ownership','소유권 이전 조건','TEXTAREA',20 UNION ALL SELECT 'car_rental','option_cost','추가 선택 시 비용','TEXT',30 UNION ALL SELECT 'car_rental','contact','차량 반환 시 연락처','TEXT',40 UNION ALL SELECT 'car_rental','breakdown','고장·훼손 시 소비자 책임','TEXTAREA',50 UNION ALL SELECT 'car_rental','cancel','예약 취소 또는 중도 해약 시 환불 기준','TEXTAREA',60 UNION ALL SELECT 'car_rental','service','소비자 상담 관련 전화번호','TEXT',70 UNION ALL
SELECT 'rental_appliance','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'rental_appliance','ownership','소유권 이전 조건','TEXTAREA',20 UNION ALL SELECT 'rental_appliance','maintenance','유지보수 조건','TEXTAREA',30 UNION ALL SELECT 'rental_appliance','damage','고장·분실·훼손 시 소비자 책임','TEXTAREA',40 UNION ALL SELECT 'rental_appliance','cancel','중도 해약 시 환불 기준','TEXTAREA',50 UNION ALL SELECT 'rental_appliance','spec','제품 사양','TEXTAREA',60 UNION ALL SELECT 'rental_appliance','service','소비자 상담 관련 전화번호','TEXT',70 UNION ALL
SELECT 'rental_goods','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'rental_goods','ownership','소유권 이전 조건','TEXTAREA',20 UNION ALL SELECT 'rental_goods','damage','상품의 고장·분실·훼손 시 소비자 책임','TEXTAREA',30 UNION ALL SELECT 'rental_goods','cancel','중도 해약 시 환불 기준','TEXTAREA',40 UNION ALL SELECT 'rental_goods','service','소비자 상담 관련 전화번호','TEXT',50 UNION ALL
SELECT 'digital_content','provider','제작자 또는 공급자','TEXT',10 UNION ALL SELECT 'digital_content','conditions','이용조건/이용기간','TEXTAREA',20 UNION ALL SELECT 'digital_content','method','상품 제공 방식','TEXT',30 UNION ALL SELECT 'digital_content','requirements','최소 시스템 사양/필수 소프트웨어','TEXTAREA',40 UNION ALL SELECT 'digital_content','withdrawal','청약철회 또는 계약 해제·해지에 따른 효과','TEXTAREA',50 UNION ALL SELECT 'digital_content','service','소비자 상담 관련 전화번호','TEXT',60 UNION ALL
SELECT 'gift_card','issuer','발행자','TEXT',10 UNION ALL SELECT 'gift_card','conditions','유효기간/이용조건','TEXTAREA',20 UNION ALL SELECT 'gift_card','stores','이용 가능 매장','TEXT',30 UNION ALL SELECT 'gift_card','refund','잔액 환급 조건','TEXTAREA',40 UNION ALL SELECT 'gift_card','service','소비자 상담 관련 전화번호','TEXT',50 UNION ALL
SELECT 'mobile_coupon','issuer','발행자','TEXT',10 UNION ALL SELECT 'mobile_coupon','conditions','유효기간/이용조건','TEXTAREA',20 UNION ALL SELECT 'mobile_coupon','stores','이용 가능 매장','TEXT',30 UNION ALL SELECT 'mobile_coupon','refund','환불조건 및 방법','TEXTAREA',40 UNION ALL SELECT 'mobile_coupon','service','소비자 상담 관련 전화번호','TEXT',50 UNION ALL
SELECT 'movie_performance','organizer','주최 또는 기획','TEXT',10 UNION ALL SELECT 'movie_performance','cast','주연','TEXT',20 UNION ALL SELECT 'movie_performance','rating','관람등급','TEXT',30 UNION ALL SELECT 'movie_performance','duration','상영·공연시간','TEXT',40 UNION ALL SELECT 'movie_performance','venue','상영·공연장소','TEXT',50 UNION ALL SELECT 'movie_performance','cancel_time','예매 취소 조건','TEXTAREA',60 UNION ALL SELECT 'movie_performance','refund','취소·환불방법','TEXTAREA',70 UNION ALL SELECT 'movie_performance','service','소비자 상담 관련 전화번호','TEXT',80 UNION ALL
SELECT 'household_chemical','labeling','화학제품안전법 및 안전확인대상생활화학제품 표시기준에 따른 표시사항','TEXTAREA',10 UNION ALL SELECT 'household_chemical','service','소비자 상담 관련 전화번호','TEXT',20 UNION ALL
SELECT 'biocidal_product','labeling','살생물제법 및 살생물제품 표시 규정에 따른 표시사항','TEXTAREA',10 UNION ALL SELECT 'biocidal_product','service','소비자 상담 관련 전화번호','TEXT',20 UNION ALL
SELECT 'other_service','provider','서비스 제공 사업자','TEXT',10 UNION ALL SELECT 'other_service','license','법에 의한 인증·허가 사항','TEXT',20 UNION ALL SELECT 'other_service','conditions','이용조건','TEXTAREA',30 UNION ALL SELECT 'other_service','cancel','취소·중도해약·해지 조건 및 환불기준','TEXTAREA',40 UNION ALL SELECT 'other_service','refund','취소·환불방법','TEXTAREA',50 UNION ALL SELECT 'other_service','service','소비자 상담 관련 전화번호','TEXT',60 UNION ALL
SELECT 'other_goods','name_model','품명 및 모델명','TEXT',10 UNION ALL SELECT 'other_goods','license','법에 의한 인증·허가 사항','TEXT',20 UNION ALL SELECT 'other_goods','country','제조국 또는 원산지','TEXT',30 UNION ALL SELECT 'other_goods','manufacturer','제조자/수입자','TEXT',40 UNION ALL SELECT 'other_goods','service','A/S 책임자와 전화번호','TEXT',50
) f ON f.c=t.type_code
WHERE t.revision='2023-01-01';
